// <auto-generated />
namespace Movies_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class moviepic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moviepic));
        
        string IMigrationMetadata.Id
        {
            get { return "202302210447215_moviepic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
